#!/usr/bin/env node
/**
 * gen-types.mjs — generate TypeScript types from the JSON Schemas
 * committed under docs/schemas/api/.
 *
 * The schemas themselves are generated by `make schema` (cmd/stem-schema)
 * from the Go DTOs in internal/api. This script runs json-schema-to-typescript
 * over each schema and writes the result into ui/src/types/generated/.
 *
 * Adding a DTO is a four-step change with all four happening
 * automatically once you've added the Go field + tag:
 *   1. add a schemaTarget entry in cmd/stem-schema/main.go
 *   2. `make schema`
 *   3. `npm run gen-types` (this script)
 *   4. consume the generated type in ui/src/
 *
 * CI gates 2/3 via scripts/check-schema-drift.sh + a sibling gate in
 * #271 for TS drift.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..');
const SCHEMA_DIR = resolve(ROOT, 'docs', 'schemas', 'api');
const OUT_DIR = resolve(ROOT, 'ui', 'src', 'types', 'generated');

const BANNER = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Regenerate with: \`npm run gen-types\` (or \`make schema && npm run gen-types\`
 * after Go DTO changes). The schema source of truth lives at
 * docs/schemas/api/; the Go DTO source lives at internal/api/.
 */
`;

async function main() {
  const entries = await readdir(SCHEMA_DIR);
  const schemas = entries.filter((f) => f.endsWith('.schema.json')).sort();

  if (schemas.length === 0) {
    console.error(`No schemas found in ${SCHEMA_DIR}`);
    process.exit(1);
  }

  const { mkdir } = await import('node:fs/promises');
  await mkdir(OUT_DIR, { recursive: true });

  for (const filename of schemas) {
    const schemaPath = resolve(SCHEMA_DIR, filename);
    const raw = await readFile(schemaPath, 'utf8');
    const schema = JSON.parse(raw);

    const ts = await compile(schema, schema.title || filename, {
      bannerComment: '',
      style: { singleQuote: true, semi: true },
      additionalProperties: false,
    });

    // Strip leading .schema.json from the filename -> .ts
    const outName = filename.replace(/\.schema\.json$/, '.ts');
    const outPath = resolve(OUT_DIR, outName);
    await writeFile(outPath, BANNER + ts);
    console.error(`wrote ${outPath}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
